version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "jeremypinto"
      - "ijahman"
      - "nvaissaud"
    assignees:
      - "jeremypinto"
      - "ijahman"
      - "nvaissaud"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
