<?php

namespace App\Console\Commands;

use App\Models\Profile;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class AssignProfileTypeStudent extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'cnut:assign-profile-type-student';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Assign the profile type student using the email';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $emails = [
            "paris-lavillette.archi.fr",
            "esitc-metz.com",
            "sciencespo.fr",
            "unilasalle.fr",
            "isep.fr",
            "univ-lyon1.fr",
            "ensg.eu",
            "ensta-bretagne.fr",
            "ens-louis-lumiere.fr",
            "isa-lille.fr",
            "inp.fr",
            "supbiotech.fr",
            "u-bordeaux.fr",
            "utt.fr",
            "univ-tours.fr",
            "univ-evry.fr",
            "audencia.com",
            "cesi.fr",
            "emlv.fr",
            "clermont-fd.archi.fr",
            "enssib.fr",
            "esam-c2.fr",
            "bsb-education.com",
            "hei.fr",
            "ipag.fr",
            "mnhn.fr",
            "univ-pau.fr",
            "utc.fr",
            "psl.eu",
            "univ-avignon.fr",
            "cnac.fr",
            "elisa-aerospace.fr",
            "efeo.fr",
            "toulouse.archi.fr",
            "ensad.fr",
            "ensatt.fr",
            "inp-toulouse.fr",
            "ipb.fr",
            "iptheologie.fr",
            "u-bourgogne.fr",
            "univ-guyane.fr",
            "uvsq.fr",
            "brest-bs.com",
            "ebi-edu.com",
            "enm.meteo.fr",
            "artsetmetiers.fr",
            "cpe.fr",
            "uco.fr",
            "ict-toulouse.fr",
            "ircom.fr",
            "univ-cotedazur.fr",
            "esta-groupe.fr",
            "cfjparis.com",
            "college-de-france.fr",
            "ece.fr",
            "purpan.fr",
            "ensma.fr",
            "esitc-paris.fr",
            "insead.edu",
            "univ-lemans.fr",
            "universita.corsica",
            "univ-rennes1.fr",
            "univ-paris1.fr",
            "imt.fr",
            "centralelille.fr",
            "conservatoiredeparis.fr",
            "efrei.fr",
            "envt.fr",
            "esiea.fr",
            "epf.fr",
            "vetagro-sup.fr",
            "rennes-sb.fr",
            "unc.nc",
            "univ-grenoble-alpes.fr",
            "junia.com",
            "ena.fr",
            "ensapc.fr",
            "ifp-school.com",
            "groupe-esa.com",
            "esitc-caen.fr",
            "isit-paris.fr",
            "insa-rennes.fr",
            "skema-bs.fr",
            "tbs-education.fr",
            "univ-poitiers.fr",
            "esa-paris.fr",
            "enit.fr",
            "excelia-group.com",
            "hear.fr",
            "insa-strasbourg.fr",
            "univ-angers.fr",
            "uha.fr",
            "univ-reunion.fr",
            "univ-rouen.fr",
            "univ-orleans.fr",
            "univ-paris8.fr",
            "yschools.fr",
            "cyu.fr",
            "enscm.fr",
            "esad-amiens.fr",
            "esff.fr",
            "ices.fr",
            "institut-agro.fr",
            "insa-toulouse.fr",
            "isara.fr",
            "supmeca.fr",
            "univ-brest.fr",
            "univ-nantes.fr",
            "univ-smb.fr",
            "cnam.fr",
            "ec-lyon.fr",
            "ensci.com",
            "esj-lille.fr",
            "inha.fr",
            "univ-jfc.fr",
            "ipsa.fr",
            "epmi.fr",
            "paris-belleville.archi.fr",
            "ensea.fr",
            "agro-bordeaux.fr",
            "estia.fr",
            "ecoledubois.fr",
            "esiee.fr",
            "sciencespo-lyon.fr",
            "sorbonne-universite.fr",
            "unicaen.fr",
            "umontpellier.fr",
            "univ-antilles.fr",
            "univ-gustave-eiffel.fr",
            "yncrea-mediterranee.fr",
            "escp.eu",
            "isen-brest.fr",
            "univ-reims.fr",
            "univ-amu.fr",
            "devenir-aviateur.fr",
            "strasbourg.archi.fr",
            "oniris-nantes.fr",
            "univ-catholille.fr",
            "itech.fr",
            "univ-ubs.fr",
            "univ-littoral.fr",
            "chec.fr",
            "ehesp.fr",
            "efa.gr",
            "entpe.fr",
            "ecole-navale.fr",
            "ieseg.fr",
            "inalco.fr",
            "isdat.fr",
            "univ-larochelle.fr",
            "univ-lorraine.fr",
            "u-paris2.fr",
            "parisnanterre.fr",
            "centrale-marseille.fr",
            "hec.edu",
            "ensiie.fr",
            "ens-lyon.eu",
            "essca.fr",
            "essec.edu",
            "esigelec.fr",
            "esilv.fr",
            "inshea.fr",
            "montpellier-bs.com",
            "universite-paris-saclay.fr",
            "istom.fr",
            "femis.fr",
            "supmaritime.fr",
            "estp.fr",
            "icp.fr",
            "sciencespo-toulouse.fr",
            "insa-centrevaldeloire.fr",
            "irtsca.fr",
            "u-bordeaux-montaigne.fr",
            "univ-lille.fr",
            "unilim.fr",
            "unistra.fr",
            "univ-paris3.fr",
            "em-normandie.com",
            "ehess.fr",
            "versailles.archi.fr",
            "ensfea.fr",
            "esadhar.fr",
            "esiee-amiens.fr",
            "sciencespo-aix.fr",
            "insep.fr",
            "u-picardie.fr",
            "univ-lyon3.fr",
            "creps-toulouse-midi-pyrenees.jeunesse-sports.gouv.fr",
            "edhec.com",
            "enac.fr",
            "enib.fr",
            "utbm.fr",
            "univ-tlse3.fr",
            "ecam-rennes.fr",
            "ec-nantes.fr",
            "esme.fr",
            "st-cyr.terre.defense.gouv.fr",
            "eseo.fr",
            "ismans.cesi.fr",
            "isipca.fr",
            "kedge.edu",
            "unimes.fr",
            "univ-rennes2.fr",
            "univ-tlse2.fr",
            "casadevelazquez.org",
            "efrome.it",
            "escom.fr",
            "estaca.fr",
            "icrennes.org",
            "sciencespo-lille.eu",
            "agrosupdijon.fr",
            "isba.fr",
            "neoma-bs.fr",
            "univ-perp.fr",
            "engees.unistra.fr",
            "ensicaen.fr",
            "epita.fr",
            "ucly.fr",
            "iae-paris.com",
            "isae-supaero.fr",
            "iscparis.com",
            "univ-lyon2.fr",
            "univ-montp3.fr",
            "uphf.fr",
            "ut-capitole.fr",
            "ecam.fr",
            "rouen.archi.fr",
            "ensc-rennes.fr",
            "ecole-paysage.fr",
            "vet-alfort.fr",
            "ens-rennes.fr",
            "esad-reims.fr",
            "sciencespobordeaux.fr",
            "ifao.egnet.net",
            "instn.cea.fr",
            "ip-paris.fr",
            "pspbb.fr",
            "u-paris.fr",
            "univ-tln.fr",
            "univ-mayotte.fr",
            "eigsi.fr",
            "ecoledulouvre.fr",
            "ecoledesponts.fr",
            "paris-malaquais.archi.fr",
            "beauxartsparis.fr",
            "esaip.org",
            "ipc-paris.fr",
            "sciencespo-rennes.fr",
            "3il-ingenieurs.fr",
            "insa-lyon.fr",
            "insa-rouen.fr",
            "itescia.fr",
            "univ-artois.fr",
            "u-pec.fr",
            "ifmparis.fr",
            "ens2m.fr",
            "ensait.fr",
            "icn-artem.com",
            "univ-fcomte.fr",
            "upf.pf",
            "univ-lehavre.fr",
            "univ-st-etienne.fr",
            "univ-paris13.fr",
            "esdes.ucly.fr",
            "vetagro-sup.fr",
            "hetic.net",
            "mines-paristech.fr",
            "sigma-clermont.fr",
            "esc-clermont.fr",
            "clermont-fd.archi.fr",
            "ecema.fr",
            "esdac-clermont.fr",
            "ac-clermont.fr",
        ];

        $queryBuilder = Profile::whereNull('type');

        $queryBuilder->where(function ($query) use ($emails) {
            foreach ($emails as $email) {
                $query->orWhere('email', 'like', '%' . $email);
            }
        });

        $this->info($queryBuilder->count() . ' profiles will be updated');
        if ($this->confirm('Do you wish to continue?')) {
            $queryBuilder->update(['type' => 'etudiant']);
        }
    }
}
