name: Tests

on: ['push', 'pull_request']

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Laravel Encryption key
        run: php artisan key:generate

      - name: Laravel Passport Keys
        run: php artisan passport:keys

      - name: Tests
        run: ./vendor/bin/pest
        env:
          TESTING_DB_HOST: localhost
          TESTING_DB_DATABASE: postgres
          TESTING_DB_USERNAME: postgres
          TESTING_DB_PASSWORD: postgres

      - name: Notify on Slack - Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: good
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: 'Tests succeeded for the Laravel app! :tada:'
          SLACK_USERNAME: Github Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on Slack - Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: danger
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: 'Tests failed for the Laravel app! :cry:'
          SLACK_USERNAME: Github Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
